### ISSUE TITLE
before_action error for rails 5.2.2

### ISSUE THREAD

**Issue by kirykr** [solidusio-contrib/solidus_papertrail#21]
I installed the gem, run bundle install, the error raised:
```ruby
/Users/kiry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/paper_trail-4.0.2/lib/paper_trail/frameworks/rails/controller.rb:6:in `included': undefined method `before_filter' for ActionController::Base:Class (NoMethodError)
Did you mean?  before_action
```

**Comment by Vicky099** [comment]
@kirykr any solution you found for this issue???

**Comment by kirykr** [comment]
@Vicky099 i haven't try the project ever since.

**Comment by Vicky099** [comment]
Just found solution. use paper_trail 5.2.0. for more info checkout compatibility table https://github.com/paper-trail-gem/paper_trail#1a-compatibility
